### ISSUE TITLE
Content Within Floorplan Card Never Loads

### ISSUE THREAD

**Issue by pldmgg** [pkozul/lovelace-floorplan#3]
Thanks for creating this lovelace card!

I followed the README.txt to implement both Simple and Ring examples. The good news is that both cards appear on my UI. Unfortunately, the content within each of those cards never actually loads (spinner animation).

At this point, I'm just trying to get the Ring example working since the configuration seems simpler.

I'm using Hassio 0.93.2 on a Raspberry Pi 3 Model B+ (64bit image). My /config directory tree looks like this:

```
.
├── automations.yaml
├── captures
│   └── backyard.jpg
├── configuration.yaml
├── customcards
│   └── github
│       └── custom-cards
│           ├── floorplan
│           │   ├── examples
│           │   │   ├── ring
│           │   │   │   ├── README.md
│           │   │   │   ├── ring.css
│           │   │   │   ├── ring.svg
│           │   │   │   └── ring.yaml
│           │   │   └── simple
│           │   │       ├── light_off.svg
│           │   │       ├── light_on.svg
│           │   │       ├── README.md
│           │   │       ├── simple.css
│           │   │       └── simple.svg
│           │   ├── floorplan-card.js
│           │   ├── floorplan.js
│           │   ├── ha-floorplan.html
│           │   ├── jquery-3.4.1.min.js
│           │   ├── lib
│           │   │   ├── floorplan.js
│           │   │   ├── jquery-3.4.1.min.js
│           │   │   └── yaml.min.js
│           │   └── yaml.min.js
│           └── tracker-card
│               └── tracker-card.js
├── custom_components
│   └── custom_updater
│       ├── __init__.py
│       ├── __pycache__
│       │   └── __init__.cpython-37.pyc
│       └── services.yaml
├── customize.yaml
├── deps
│   └── lib
│       └── python3.7
│           └── site-packages
│               ├── pyupdate
│               │   ├── ha_custom
│               │   │   ├── common.py
│               │   │   ├── custom_cards.py
│               │   │   ├── custom_components.py
│               │   │   ├── __init__.py
│               │   │   ├── __pycache__
│               │   │   │   ├── common.cpython-37.pyc
│               │   │   │   ├── custom_cards.cpython-37.pyc
│               │   │   │   ├── custom_components.cpython-37.pyc
│               │   │   │   ├── __init__.cpython-37.pyc
│               │   │   │   └── python_scripts.cpython-37.pyc
│               │   │   └── python_scripts.py
│               │   ├── __init__.py
│               │   ├── log.py
│               │   ├── __pycache__
│               │   │   ├── __init__.cpython-37.pyc
│               │   │   ├── log.cpython-37.pyc
│               │   │   └── self.cpython-37.pyc
│               │   └── self.py
│               └── pyupdate-1.4.0.dist-info
│                   ├── INSTALLER
│                   ├── METADATA
│                   ├── RECORD
│                   ├── top_level.txt
│                   └── WHEEL
├── groups.yaml
├── harmony_harmony_hub.conf
├── home-assistant.log
├── home-assistant_v2.db
├── scripts.yaml
├── secrets.yaml
├── tts
└── www
    └── github
        └── custom-cards
            ├── floorplan
            │   ├── examples
            │   │   ├── ring
            │   │   │   ├── README.md
            │   │   │   ├── ring.css
            │   │   │   ├── ring.svg
            │   │   │   └── ring.yaml
            │   │   └── simple
            │   │       ├── light_off.svg
            │   │       ├── light_on.svg
            │   │       ├── README.md
            │   │       ├── simple.css
            │   │       └── simple.svg
            │   ├── floorplan-card.js
            │   ├── floorplan.js
            │   ├── ha-floorplan.html
            │   ├── jquery-3.4.1.min.js
            │   ├── lib
            │   │   ├── floorplan.js
            │   │   ├── jquery-3.4.1.min.js
            │   │   └── yaml.min.js
            │   └── yaml.min.js
            ├── tracker-card
            │   └── tracker-card.js
            └── tracker-card.js
```

My `/config/www/github/custom-cards/floorplan/examples/ring/ring/ring.yaml` and `/config/customcards/github/custom-cards/floorplan/examples/ring/ring/ring.yaml` look like this:

```
image: /customcards/github/custom-cards/floorplan/examples/ring/ring.svg
stylesheet: /customcards/github/custom-cards/floorplan/examples/ring/ring.css

rules:
  - entity: sensor.ring_front_door_battery
    text_template: '${entity.state ? entity.state + "%" : "unknown"}'

  - entities:
      - binary_sensor.ring_front_door_motion
    states:
      - state: 'on'
        class: 'ring-motion'

  - entity: binary_sensor.ring_front_door_ding
    states:
      - state: 'on'
        class: 'ring-ding'
```

(I've also tried with the above `image:` and `stylesheet:` entries pointing to `/www/github/custom-cards/floorplan/examples/ring/ring.svg` and `/www/github/custom-cards/floorplan/examples/ring/ring.css` with the same result - i.e. spinner animation)

The relevant portions of my lovelace-ui config look like this:

```
resources:
  - type: module
    url: /customcards/github/custom-cards/tracker-card/tracker-card.js?track=true
  - type: module
    url: /customcards/github/custom-cards/floorplan/floorplan-card.js?v=1.1.14
title: Home
views:
```
...
```
  - cards:
      - config: /customcards/github/custom-cards/floorplan/examples/ring/ring.yaml
        title: Ring
        type: 'custom:floorplan-card'
    icon: 'mdi:floor-plan'
    id: system
    panel: false
    path: floorplan
    title: Floorplan
```

I also made sure that all of the relevant `inkscape:label=` and `id=` entries in `ring.svg` (both under `/config/customcards/.../ring.svg` and `/config/www/.../ring.svg` refer to real entities in my HA configuration.

I'm pretty sure the issue is that the module can't find some of the files it needs, but I'm not sure how to go about fixing the situation. (I tried copying the files within `floorplan/lib/` everywhere I could think of, but that didn't seem to make a difference).
