### ISSUE TITLE
any plans on adding css rules?

### ISSUE THREAD

**Issue by SerdarSanri** [pkozul/lovelace-floorplan#31]
I was wondering if you have any plans to implement change style rules by state? What I meant is similar to toggling classes by state, it would be great to manipulate style properties by state or attributes. so for instance from cover entity we can retrieve position and animate a blind svg image by adjusting transform with mask. Or for battery sensors we can create a simple green bar and update width or height ( depending on position ) by percentage to lower higher value.  

You may think this can be done with classes too and yes definitely but for accurate animation etc, you have to create bunch of classes like open-5-percent, open-10-percent.... open-100-percent etc.

**Comment by pbavinck** [comment]
Toggling classes can be accomplished using `service: floorplan.class_toggle` in the action setting. Here is an example from my yaml:
```yaml
  - name: FF Selector
    elements:
      - ff_selector
    action:
      service: floorplan.class_toggle
      data:
        elements:
          - first_floor
        classes:
          - object-visible
          - object-hidden
        default_class: object-hidden
```

**Comment by exetico** [comment]
I'm using this, and that's working just fine.
```
name: Office Spotlys
entities:
  - group.office
element: area.office
action:
  service: light.toggle
  data:
    entity_id: light.spotlys_kontor
states:
  - state: 'on'
    class: 'light-on'
  - state: 'off'
    class: 'light-off'
```
