### ISSUE TITLE
URL Links

### ISSUE THREAD

**Issue by NetAgentTV** [pkozul/lovelace-floorplan#36]
I've managed to call a URL by clicking on an element working by adding the following code to **lib/floorplan.js**

After line 1526, add the following (add it above the "_case 'variable_set':_" line)
```
        case 'url_navigate':
          const url_link = actionData.page_id;
          window.location.href = url_link;
          break;
          
        case 'url_navigate_new':
          const url_newlink = actionData.page_id;
          window.open(url_newlink, '_blank');
          break;

```

It can be called using (opens in same tab/window):
```
- action:
  service: floorplan.url_navigate
  data:
    page_id: 'rtsp://<user>:<pass>@<cam_ip>:554/cam/realmonitor?channel=1?subtype=1'
  element: cam1
  entity: camera.front_yard
```

To open the link in a new window/tab:
```
- action:
  service: floorplan.url_navigate_new
  data:
    page_id: 'https://github.com'
  element: cam1
  entity: camera.front_yard
```

Any link _should_ work. Note for the RTSP camera link, I've enabled Firefox to open VLC for RTSP links.
