### ISSUE TITLE
Image element not replaced

### ISSUE THREAD

**Issue by b0c1** [pkozul/lovelace-floorplan#7]
I have an element with:
```yaml
            - element: weather_radar
              image: 'https://www.idokep.hu/kistersegi/riaszt_24.png'
              image_refresh_interval: 12
```
I see in the console, the image fetched . The SVG element (rect id="weather_radar") is clickable, but the image not visible.
